[project]
name = "alpaca-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alpaca-py>=0.40.1",
    "alpaca-trade-api>=3.2.0",
    "mcp>=1.9.3",
    "python-dotenv>=1.1.0",
    "psutil>=5.9.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "mypy>=1.16.0",
    "ruff>=0.11.13",
]
